USE openemr;

CREATE TABLE IF NOT EXISTS users (
  id bigint(20) NOT NULL auto_increment,
  username varchar(255) default NULL,
  password longtext,
  authorized tinyint(4) default NULL,
  info longtext,
  source tinyint(4) default NULL,
  fname varchar(255) default NULL,
  mname varchar(255) default NULL,
  lname varchar(255) default NULL,
  suffix varchar(255) default NULL,
  federaltaxid varchar(255) default NULL,
  federaldrugid varchar(255) default NULL,
  upin varchar(255) default NULL,
  facility varchar(255) default NULL,
  facility_id int(11) NOT NULL default '0',
  see_auth int(11) NOT NULL default '1',
  active tinyint(1) NOT NULL default '1',
  npi varchar(15) default NULL,
  title varchar(30) default NULL,
  specialty varchar(255) default NULL,
  billname varchar(255) default NULL,
  email varchar(255) default NULL,
  email_direct varchar(255) NOT NULL default '',
  google_signin_email VARCHAR(255) UNIQUE DEFAULT NULL,
  url varchar(255) default NULL,
  assistant varchar(255) default NULL,
  organization varchar(255) default NULL,
  valedictory varchar(255) default NULL,
  street varchar(60) default NULL,
  streetb varchar(60) default NULL,
  city varchar(30) default NULL,
  state varchar(30) default NULL,
  zip varchar(20) default NULL,
  street2 varchar(60) default NULL,
  streetb2 varchar(60) default NULL,
  city2 varchar(30) default NULL,
  state2 varchar(30) default NULL,
  zip2 varchar(20) default NULL,
  phone varchar(30) default NULL,
  fax varchar(30) default NULL,
  phonew1 varchar(30) default NULL,
  phonew2 varchar(30) default NULL,
  phonecell varchar(30) default NULL,
  notes text,
  cal_ui tinyint(4) NOT NULL default '1',
  taxonomy varchar(30) NOT NULL DEFAULT '207Q00000X',
  calendar TINYINT(1) NOT NULL DEFAULT 0 COMMENT '1 = appears in calendar',
  abook_type varchar(31) NOT NULL DEFAULT '',
  default_warehouse varchar(31) NOT NULL DEFAULT '',
  PRIMARY KEY (id),
  UNIQUE KEY username (username)
) ENGINE=InnoDB;

INSERT INTO users (id, username, password, authorized, active, fname, lname, email) 
VALUES (1, 'admin', '21232f297a57a5a743894a0e4a801fc3', 1, 1, 'Admin', 'User', 'admin@localhost');

