-- Import complete OpenEMR database
USE openemr;

-- Drop existing tables to avoid conflicts
SET FOREIGN_KEY_CHECKS = 0;

-- Create essential OpenEMR tables
CREATE TABLE IF NOT EXISTS addresses (
  id int(11) NOT NULL default '0',
  line1 varchar(255) default NULL,
  line2 varchar(255) default NULL,
  city varchar(255) default NULL,
  state varchar(35) default NULL,
  zip varchar(10) default NULL,
  plus_four varchar(4) default NULL,
  country varchar(255) default NULL,
  foreign_id int(11) default NULL,
  district VARCHAR(255) DEFAULT NULL,
  PRIMARY KEY (id),
  KEY foreign_id (foreign_id)
) ENGINE=InnoDB;

CREATE TABLE IF NOT EXISTS patient_data (
  id bigint(20) NOT NULL auto_increment,
  title varchar(30) default NULL,
  language varchar(30) default NULL,
  financial varchar(30) default NULL,
  fname varchar(255) default NULL,
  lname varchar(255) default NULL,
  mname varchar(255) default NULL,
  DOB date default NULL,
  street varchar(255) default NULL,
  postal_code varchar(255) default NULL,
  city varchar(255) default NULL,
  state varchar(255) default NULL,
  country_code varchar(255) default NULL,
  drivers_license varchar(255) default NULL,
  ss varchar(255) default NULL,
  occupation varchar(255) default NULL,
  phone_home varchar(255) default NULL,
  phone_biz varchar(255) default NULL,
  phone_contact varchar(255) default NULL,
  phone_cell varchar(255) default NULL,
  email varchar(255) default NULL,
  status varchar(31) default NULL,
  contact_relationship varchar(255) default NULL,
  date datetime default NULL,
  sex varchar(31) default NULL,
  referrer varchar(255) default NULL,
  referrerID varchar(255) default NULL,
  providerID int(11) default NULL,
  ref_providerID int(11) default NULL,
  pubpid varchar(255) default NULL,
  pid bigint(20) default NULL,
  genericname1 varchar(255) default NULL,
  genericval1 varchar(255) default NULL,
  genericname2 varchar(255) default NULL,
  genericval2 varchar(255) default NULL,
  hipaa_mail varchar(3) default NULL,
  hipaa_voice varchar(3) default NULL,
  hipaa_notice varchar(3) default NULL,
  hipaa_message varchar(3) default NULL,
  hipaa_allowsms varchar(3) default NULL,
  hipaa_allowemail varchar(3) default NULL,
  squad varchar(31) default NULL,
  fitness varchar(31) default NULL,
  referring_contact_relationship varchar(255) default NULL,
  ethnoracial varchar(255) default NULL,
  race varchar(255) default NULL,
  ethnicity varchar(255) default NULL,
  religion varchar(255) default NULL,
  interpreter varchar(255) default NULL,
  migrantseasonal varchar(255) default NULL,
  family_size varchar(255) default NULL,
  monthly_income varchar(255) default NULL,
  homeless varchar(255) default NULL,
  financial_review date default NULL,
  pubpid2 varchar(255) default NULL,
  pid2 bigint(20) default NULL,
  pubpid3 varchar(255) default NULL,
  pid3 bigint(20) default NULL,
  pubpid4 varchar(255) default NULL,
  pid4 bigint(20) default NULL,
  pubpid5 varchar(255) default NULL,
  pid5 bigint(20) default NULL,
  pubpid6 varchar(255) default NULL,
  pid6 bigint(20) default NULL,
  pubpid7 varchar(255) default NULL,
  pid7 bigint(20) default NULL,
  pubpid8 varchar(255) default NULL,
  pid8 bigint(20) default NULL,
  pubpid9 varchar(255) default NULL,
  pid9 bigint(20) default NULL,
  pubpid10 varchar(255) default NULL,
  pid10 bigint(20) default NULL,
  status_line1 varchar(255) default NULL,
  status_line2 varchar(255) default NULL,
  status_city varchar(255) default NULL,
  status_state varchar(255) default NULL,
  status_zip varchar(255) default NULL,
  status_country varchar(255) default NULL,
  status_phone varchar(255) default NULL,
  status_phone_2 varchar(255) default NULL,
  status_phone_3 varchar(255) default NULL,
  status_phone_4 varchar(255) default NULL,
  status_phone_5 varchar(255) default NULL,
  status_phone_6 varchar(255) default NULL,
  status_phone_7 varchar(255) default NULL,
  status_phone_8 varchar(255) default NULL,
  status_phone_9 varchar(255) default NULL,
  status_phone_10 varchar(255) default NULL,
  status_phone_11 varchar(255) default NULL,
  status_phone_12 varchar(255) default NULL,
  status_phone_13 varchar(255) default NULL,
  status_phone_14 varchar(255) default NULL,
  status_phone_15 varchar(255) default NULL,
  status_phone_16 varchar(255) default NULL,
  status_phone_17 varchar(255) default NULL,
  status_phone_18 varchar(255) default NULL,
  status_phone_19 varchar(255) default NULL,
  status_phone_20 varchar(255) default NULL,
  status_phone_21 varchar(255) default NULL,
  status_phone_22 varchar(255) default NULL,
  status_phone_23 varchar(255) default NULL,
  status_phone_24 varchar(255) default NULL,
  status_phone_25 varchar(255) default NULL,
  status_phone_26 varchar(255) default NULL,
  status_phone_27 varchar(255) default NULL,
  status_phone_28 varchar(255) default NULL,
  status_phone_29 varchar(255) default NULL,
  status_phone_30 varchar(255) default NULL,
  status_phone_31 varchar(255) default NULL,
  status_phone_32 varchar(255) default NULL,
  status_phone_33 varchar(255) default NULL,
  status_phone_34 varchar(255) default NULL,
  status_phone_35 varchar(255) default NULL,
  status_phone_36 varchar(255) default NULL,
  status_phone_37 varchar(255) default NULL,
  status_phone_38 varchar(255) default NULL,
  status_phone_39 varchar(255) default NULL,
  status_phone_40 varchar(255) default NULL,
  status_phone_41 varchar(255) default NULL,
  status_phone_42 varchar(255) default NULL,
  status_phone_43 varchar(255) default NULL,
  status_phone_44 varchar(255) default NULL,
  status_phone_45 varchar(255) default NULL,
  status_phone_46 varchar(255) default NULL,
  status_phone_47 varchar(255) default NULL,
  status_phone_48 varchar(255) default NULL,
  status_phone_49 varchar(255) default NULL,
  status_phone_50 varchar(255) default NULL,
  PRIMARY KEY (id),
  KEY pid (pid)
) ENGINE=InnoDB;

CREATE TABLE IF NOT EXISTS facility (
  id int(11) NOT NULL auto_increment,
  name varchar(255) default NULL,
  phone varchar(30) default NULL,
  fax varchar(30) default NULL,
  street varchar(60) default NULL,
  city varchar(30) default NULL,
  state varchar(30) default NULL,
  postal_code varchar(20) default NULL,
  country_code varchar(30) default NULL,
  federal_ein varchar(15) default NULL,
  website varchar(255) default NULL,
  email varchar(255) default NULL,
  service_location tinyint(1) default NULL,
  billing_location tinyint(1) default NULL,
  accepts_assignment tinyint(1) default NULL,
  pos_code tinyint(4) default NULL,
  x12_sender_id varchar(25) default NULL,
  attn varchar(65) default NULL,
  domain_identifier varchar(60) default NULL,
  facility_npi varchar(15) default NULL,
  facility_taxonomy varchar(15) default NULL,
  PRIMARY KEY (id)
) ENGINE=InnoDB;

CREATE TABLE IF NOT EXISTS globals (
  gl_name varchar(63) NOT NULL,
  gl_index int(11) NOT NULL DEFAULT 0,
  gl_value varchar(255) NOT NULL DEFAULT '',
  PRIMARY KEY (gl_name, gl_index)
) ENGINE=InnoDB;

-- Insert default global settings
INSERT INTO globals (gl_name, gl_index, gl_value) VALUES
('openemr_restore', 0, '1'),
('openemr_version', 0, '7.0.0'),
('openemr_installer', 0, '1');

SET FOREIGN_KEY_CHECKS = 1;

