-- Inventory Audit System Database Schema
-- This file creates all necessary tables and triggers for the comprehensive inventory audit system

-- Table: inventory_movement_log
-- Stores detailed audit trail of all inventory movements
CREATE TABLE IF NOT EXISTS `inventory_movement_log` (
  `log_id` int(11) NOT NULL AUTO_INCREMENT,
  `drug_id` int(11) NOT NULL,
  `inventory_id` int(11) NOT NULL,
  `warehouse_id` varchar(31) DEFAULT NULL,
  `movement_type` varchar(50) NOT NULL,
  `quantity_before` decimal(10,2) NOT NULL DEFAULT 0.00,
  `quantity_change` decimal(10,2) NOT NULL,
  `quantity_after` decimal(10,2) NOT NULL DEFAULT 0.00,
  `reference_id` int(11) DEFAULT NULL,
  `reference_type` varchar(50) DEFAULT NULL,
  `lot_number` varchar(50) DEFAULT NULL,
  `expiration_date` date DEFAULT NULL,
  `unit_cost` decimal(10,2) DEFAULT NULL,
  `total_value` decimal(10,2) DEFAULT NULL,
  `reason` varchar(255) DEFAULT NULL,
  `notes` text DEFAULT NULL,
  `user_id` int(11) NOT NULL,
  `ip_address` varchar(45) DEFAULT NULL,
  `movement_date` datetime NOT NULL DEFAULT CURRENT_TIMESTAMP,
  PRIMARY KEY (`log_id`),
  KEY `idx_drug_id` (`drug_id`),
  KEY `idx_inventory_id` (`inventory_id`),
  KEY `idx_warehouse_id` (`warehouse_id`),
  KEY `idx_movement_type` (`movement_type`),
  KEY `idx_user_id` (`user_id`),
  KEY `idx_movement_date` (`movement_date`),
  KEY `idx_reference` (`reference_type`, `reference_id`),
  KEY `idx_ip_address` (`ip_address`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

-- Table: inventory_settings
-- Stores configuration settings for the audit system
CREATE TABLE IF NOT EXISTS `inventory_settings` (
  `setting_id` int(11) NOT NULL AUTO_INCREMENT,
  `setting_name` varchar(100) NOT NULL,
  `setting_value` text DEFAULT NULL,
  `setting_description` text DEFAULT NULL,
  `is_global` tinyint(1) NOT NULL DEFAULT 1,
  `facility_id` int(11) DEFAULT NULL,
  `created_date` datetime NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `modified_date` datetime DEFAULT NULL ON UPDATE CURRENT_TIMESTAMP,
  PRIMARY KEY (`setting_id`),
  UNIQUE KEY `uk_setting_name_facility` (`setting_name`, `facility_id`),
  KEY `idx_setting_name` (`setting_name`),
  KEY `idx_is_global` (`is_global`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

-- Table: inventory_alerts
-- Stores alerts generated by the audit system
CREATE TABLE IF NOT EXISTS `inventory_alerts` (
  `alert_id` int(11) NOT NULL AUTO_INCREMENT,
  `drug_id` int(11) NOT NULL,
  `warehouse_id` varchar(31) DEFAULT NULL,
  `alert_type` varchar(50) NOT NULL,
  `message` text NOT NULL,
  `threshold_value` decimal(10,2) DEFAULT NULL,
  `current_value` decimal(10,2) DEFAULT NULL,
  `is_active` tinyint(1) NOT NULL DEFAULT 1,
  `acknowledged_date` datetime DEFAULT NULL,
  `acknowledged_by` int(11) DEFAULT NULL,
  `created_date` datetime NOT NULL DEFAULT CURRENT_TIMESTAMP,
  PRIMARY KEY (`alert_id`),
  KEY `idx_drug_id` (`drug_id`),
  KEY `idx_warehouse_id` (`warehouse_id`),
  KEY `idx_alert_type` (`alert_type`),
  KEY `idx_is_active` (`is_active`),
  KEY `idx_created_date` (`created_date`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

-- Table: inventory_audit_reports
-- Stores generated audit reports
CREATE TABLE IF NOT EXISTS `inventory_audit_reports` (
  `report_id` int(11) NOT NULL AUTO_INCREMENT,
  `report_name` varchar(100) NOT NULL,
  `report_type` varchar(50) NOT NULL,
  `report_parameters` text DEFAULT NULL,
  `generated_by` int(11) NOT NULL,
  `generated_date` datetime NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `file_path` varchar(255) DEFAULT NULL,
  `file_size` int(11) DEFAULT NULL,
  `is_archived` tinyint(1) NOT NULL DEFAULT 0,
  PRIMARY KEY (`report_id`),
  KEY `idx_report_type` (`report_type`),
  KEY `idx_generated_by` (`generated_by`),
  KEY `idx_generated_date` (`generated_date`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

-- Insert default audit settings
INSERT IGNORE INTO `inventory_settings` (`setting_name`, `setting_value`, `setting_description`, `is_global`) VALUES
('audit_trail_enabled', '1', 'Enable comprehensive audit trail for inventory movements', 1),
('audit_retention_days', '365', 'Number of days to retain audit records', 1),
('audit_log_level', 'standard', 'Audit log level: minimal, standard, detailed', 1),
('audit_email_notifications', '0', 'Enable email notifications for audit events', 1),
('audit_alert_threshold', '100', 'Threshold for generating movement alerts', 1),
('audit_auto_cleanup', '0', 'Enable automatic cleanup of old audit records', 1),
('audit_backup_enabled', '0', 'Enable backup before cleanup operations', 1),
('audit_export_format', 'csv', 'Default export format for audit reports', 1),
('low_stock_threshold_days', '30', 'Days of stock remaining to trigger low stock alert', 1),
('expiration_warning_days', '90', 'Days before expiration to trigger warning', 1);

-- Create triggers for automatic audit logging

-- Trigger: trg_drug_sales_audit
-- Automatically logs sales transactions
DELIMITER $$
CREATE TRIGGER IF NOT EXISTS `trg_drug_sales_audit` 
AFTER INSERT ON `drug_sales` 
FOR EACH ROW 
BEGIN
    DECLARE v_user_id INT DEFAULT NULL;
    DECLARE v_facility_id VARCHAR(31) DEFAULT NULL;
    
    -- Get current user from session or default
    SET v_user_id = IFNULL(@current_user_id, 1);
    SET v_facility_id = IFNULL(@current_facility_id, 'default');
    
    -- Log the sale movement
    INSERT INTO inventory_movement_log (
        drug_id, inventory_id, warehouse_id, movement_type,
        quantity_before, quantity_change, quantity_after,
        reference_id, reference_type, lot_number, expiration_date,
        unit_cost, total_value, reason, notes, user_id, ip_address, movement_date
    ) VALUES (
        NEW.drug_id, NEW.inventory_id, NEW.warehouse_id, 'sale',
        (SELECT on_hand FROM drug_inventory WHERE inventory_id = NEW.inventory_id),
        -NEW.quantity, 
        (SELECT on_hand - NEW.quantity FROM drug_inventory WHERE inventory_id = NEW.inventory_id),
        NEW.sale_id, 'drug_sale', 
        (SELECT lot_number FROM drug_inventory WHERE inventory_id = NEW.inventory_id),
        (SELECT expiration FROM drug_inventory WHERE inventory_id = NEW.inventory_id),
        NEW.unit_price, NEW.quantity * NEW.unit_price,
        'Sale transaction', 'Automatic audit log', v_user_id, IFNULL(@current_ip_address, NULL), NOW()
    );
END$$
DELIMITER ;

-- Trigger: trg_drug_inventory_update_audit
-- Logs inventory updates
DELIMITER $$
CREATE TRIGGER IF NOT EXISTS `trg_drug_inventory_update_audit` 
AFTER UPDATE ON `drug_inventory` 
FOR EACH ROW 
BEGIN
    DECLARE v_user_id INT DEFAULT NULL;
    DECLARE v_facility_id VARCHAR(31) DEFAULT NULL;
    DECLARE v_movement_type VARCHAR(50) DEFAULT 'adjustment';
    
    -- Get current user from session or default
    SET v_user_id = IFNULL(@current_user_id, 1);
    SET v_facility_id = IFNULL(@current_facility_id, 'default');
    
    -- Determine movement type based on changes
    IF NEW.on_hand > OLD.on_hand THEN
        SET v_movement_type = 'addition';
    ELSEIF NEW.on_hand < OLD.on_hand THEN
        SET v_movement_type = 'reduction';
    END IF;
    
    -- Only log if quantity changed
    IF NEW.on_hand != OLD.on_hand THEN
        INSERT INTO inventory_movement_log (
            drug_id, inventory_id, warehouse_id, movement_type,
            quantity_before, quantity_change, quantity_after,
            reference_id, reference_type, lot_number, expiration_date,
            unit_cost, total_value, reason, notes, user_id, ip_address, movement_date
        ) VALUES (
            NEW.drug_id, NEW.inventory_id, NEW.warehouse_id, v_movement_type,
            OLD.on_hand, NEW.on_hand - OLD.on_hand, NEW.on_hand,
            NULL, 'inventory_update', NEW.lot_number, NEW.expiration,
            NEW.cost_per_unit, ABS(NEW.on_hand - OLD.on_hand) * NEW.cost_per_unit,
            'Inventory adjustment', 'Automatic audit log', v_user_id, IFNULL(@current_ip_address, NULL), NOW()
        );
    END IF;
END$$
DELIMITER ;

-- Create indexes for better performance
CREATE INDEX IF NOT EXISTS `idx_movement_log_composite` ON `inventory_movement_log` (`drug_id`, `movement_date`);
CREATE INDEX IF NOT EXISTS `idx_movement_log_user_date` ON `inventory_movement_log` (`user_id`, `movement_date`);
CREATE INDEX IF NOT EXISTS `idx_alerts_active_date` ON `inventory_alerts` (`is_active`, `created_date`);

-- Add comments to tables
ALTER TABLE `inventory_movement_log` COMMENT = 'Comprehensive audit trail for all inventory movements';
ALTER TABLE `inventory_settings` COMMENT = 'Configuration settings for the inventory audit system';
ALTER TABLE `inventory_alerts` COMMENT = 'Alerts generated by the audit system for unusual activities';
ALTER TABLE `inventory_audit_reports` COMMENT = 'Generated audit reports and exports'; 